import json, requests

location = str(input())
url_apixu = 'http://api.apixu.com/v1/forecast.json?key=209e4be4a40a421ab34160306191302&q=%s&days=10' % (location)
response = requests.get(url_apixu)
w = json.loads(response.text)
print(w['location'])
print(w['current']['last_updated'], w['current']['temp_c'], w['current']['condition']['icon'])
print(w['forecast']['forecastday'][0]['date'], w['forecast']['forecastday'][0]['day'])
print(w['forecast']['forecastday'][1]['date'], w['forecast']['forecastday'][1]['day'])
print(w['forecast']['forecastday'][2]['date'], w['forecast']['forecastday'][2]['day'])
print(w['forecast']['forecastday'][3]['date'], w['forecast']['forecastday'][3]['day'])
print(w['forecast']['forecastday'][4]['date'], w['forecast']['forecastday'][4]['day'])
print(w['forecast']['forecastday'][5]['date'], w['forecast']['forecastday'][5]['day'])
print(w['forecast']['forecastday'][6]['date'], w['forecast']['forecastday'][6]['day'])